[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pushsolanalocker = "FVnnKN3tmbSuWcHbc8anrXZnzETHn96FdaKcJxamrfFx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./phantom-keypair.json"
# cluster = "https://api.devnet.solana.com"
# wallet = "./phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
